# Generated by Django 5.1.2 on 2024-11-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_referralcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReferralCode",
        ),
    ]
