# Generated by Django 5.1.2 on 2024-11-11 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="invite_code",
            field=models.CharField(blank=True, default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
